more fixes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -136,8 +136,9 @@ runs:
         log_info "Downloading platform-specific version '${{ inputs.vault-release }}' of cosign...\n      https://releases.hashicorp.com/vault/${{ inputs.vault-release }}/${desired_vault_filename}"
         $SUDO curl -sL https://releases.hashicorp.com/vault/${{ inputs.vault-release }}/${desired_vault_filename} -o ${desired_vault_filename}
         $SUDO curl -sL https://releases.hashicorp.com/vault/${{ inputs.vault-release }}/vault_${{ inputs.vault-release }}_SHA256SUMS -o SHA256SUMS
-
-        if [[ echo "$(sha256sum ${desired_vault_filename})" | sha256sum --ignore-missing --check SHA256SUMS) ]]; then
+        echo "$(sha256sum ${desired_vault_filename})" | sha256sum --ignore-missing --check SHA256SUMS)
+        ret=$?
+        if [[ $retVal -eq 0 ]]; then
           $SUDO tar xvf ${desired_vault_filename} -C ${{ inputs.install-dir }}
           $SUDO rm SHA256SUMS ${desired_vault_filename}
           log_info "Installation complete!"
